In [11]:
import pandas as pd

In [12]:
df = pd.read_csv("../data/houses.csv")

In [13]:
df.head()

   Bedrooms  Area Location  Age    Price
0         1   550   Mumbai   15  6200000
1         1   650     Pune   10  4800000
2         2   750   Mumbai   12  8200000
3         2   850     Pune    8  6100000
4         2   900   Mumbai    5  9800000

In [14]:
df["Price"].describe()

count    1.000000e+02
mean     1.270400e+07
std      5.333862e+06
min      4.800000e+06
25%      8.350000e+06
50%      1.155000e+07
75%      1.687500e+07
max      2.650000e+07
Name: Price, dtype: float64

In [15]:
df["Location"].unique()

array(['Mumbai', 'Pune'], dtype=object)

In [16]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False)

location_encoded = encoder.fit_transform(df[["Location"]])

In [17]:
location_encoded

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.]])

In [18]:
location_df = pd.DataFrame(
    location_encoded,
    columns=encoder.get_feature_names_out(["Location"]),
    index=df.index
)

In [19]:
location_df.head()

   Location_Mumbai  Location_Pune
0              1.0            0.0
1              0.0            1.0
2              1.0            0.0
3              0.0            1.0
4              1.0            0.0

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
numeric_features = df[["Bedrooms", "Area", "Age"]]

location_df = pd.DataFrame(
    location_encoded,
    columns=encoder.get_feature_names_out(["Location"]),
    index=df.index
)

X = pd.concat([numeric_features, location_df], axis=1)
y = df["Price"]

In [22]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [23]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(80, 5)
(20, 5)
(80,)
(20,)

In [24]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

LinearRegression()

In [25]:
model.fit(X_train, y_train)

LinearRegression()

In [26]:
predictions = model.predict(X_test)

In [27]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test, predictions)

print("MAE:", mae)

MAE: 904238.5283445694

In [28]:
comparison = pd.DataFrame({
    "Actual Price": y_test.values,
    "Predicted Price": predictions
})

comparison

    Actual Price  Predicted Price
0        6900000     5.940744e+06
1       11500000     1.247200e+07
2       14900000     1.548979e+07
3        7900000     7.664616e+06
4       10100000     1.116372e+07
5       18400000     1.992589e+07
6        7900000     8.965765e+06
7        6000000     6.665187e+06
8       13800000     1.406077e+07
9        6200000     6.475837e+06
10      26000000     2.242479e+07
11      15100000     1.560205e+07
12      12100000     1.309351e+07
13      11800000     1.246862e+07
14      15300000     1.556688e+07
15       9800000     1.079177e+07
16      19400000     2.023647e+07
17      16400000     1.706739e+07
18      18000000     1.650878e+07
19      11000000     1.147805e+07

In [29]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test, predictions)

print("R²:", r2)

R²: 0.9469786231960906

In [30]:
for feature, coefficient in zip(X_train.columns, model.coef_):
    print(f"{feature}: {coefficient:,.2f}")

print("Intercept:", model.intercept_)

Bedrooms: 647,046.63
Area: 7,371.53
Age: -108,885.60
Location_Mumbai: 2,300,731.59
Location_Pune: -2,300,731.59
Intercept: 1107002.2505642101

In [31]:
new_house = pd.DataFrame({
    "Bedrooms": [3],
    "Area": [1200],
    "Age": [5],
    "Location_Mumbai": [1],
    "Location_Pune": [0]
})

In [33]:
predicted_price = model.predict(new_house)

print("Predicted Price:", predicted_price[0])

Predicted Price: 13650278.82708612

In [34]:
import joblib

joblib.dump(model, "../models/model.pkl")

['../models/model.pkl']